### ISSUE TITLE
Get IPMS lab test concepts from schema

### ISSUE THREAD

**Issue by pmanko** [B-TECHBW/bw-lab-ig#19]
The IPMS schema is a flat schema found here: https://docs.google.com/spreadsheets/d/1sBvcZNa68XNV1PHrGCQIQ8jCl9z3Q4c1vzywnDuKr-A/edit?usp=sharing

We need to identify the tables/location of lab test concepts used in IPMS, and download those tables to have access to the values so we can create Value Sets/Coding Systems for IPMS concepts.

**Comment by pmanko** [comment]
@tkgakge do you have any info about the naming scheme for the IPMS schema? 

Do we need to look anywhere beyond the `DLab` prefix?

What's the difference between the `Lab` prefix or `DLab` prefix?

Candidate tables:

```
DLabConceptDescReferences
DLabConceptDescs
DLabConceptIcdDiagnoses
DLabConceptMarkers
DLabConceptReferences
DLabConceptReflexOrdGrps
DLabConceptRelationships
DLabConcepts
DLabConceptTypes
```

**Comment by pmanko** [comment]
@tkgakge If you could get the contents of these candidate tables and do a quick cross-reference with what shows up when a practitioner is ordering a lab test in IPMS as soon as you can, that would be very helpful.

**Comment by tkgakge** [comment]
Managed to get the contents for the following tables 

DLabConceptDescReferences
DLabConceptDescs
DLabConceptReferences
DLabConceptRelationships
DLabConcepts
DLabConceptTypes

The other tables where empty tables.
Did not manage to link these tables with the front end app as i was not able to login to the application. I am working resolving my login credentials
