### ISSUE TITLE
Download IPMS schema and create ER diagrams

### ISSUE THREAD

**Issue by pmanko** [B-TECHBW/bw-lab-ig#4]
In order to be able to create mappings between IPMS and the data we need for lab orders and patients in the SHR and MPI, we need to have access to the IPMS schema and a quick way to understand the schema.

**Comment by tkgakge** [comment]
Was able to get the IPMS schema but was not able to get the ER diagram as IPMS uses a flat schema, everything is under DBO schema

**Comment by pmanko** [comment]
location of schema: https://docs.google.com/spreadsheets/d/1sBvcZNa68XNV1PHrGCQIQ8jCl9z3Q4c1vzywnDuKr-A/edit?usp=sharing

Thanks @tkgakge !
